// Code generated by mockery v2.38.0. DO NOT EDIT.

package services

import (
	context "context"

	dto "github.com/radityacandra/go-project-mongodb/internal/application/cctv/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockIService) Create(ctx context.Context, req dto.CreateRequest) (dto.CreateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateRequest) (dto.CreateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateRequest) dto.CreateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CreateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateRequest
func (_e *MockIService_Expecter) Create(ctx interface{}, req interface{}) *MockIService_Create_Call {
	return &MockIService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockIService_Create_Call) Run(run func(ctx context.Context, req dto.CreateRequest)) *MockIService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateRequest))
	})
	return _c
}

func (_c *MockIService_Create_Call) Return(_a0 dto.CreateResponse, _a1 error) *MockIService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_Create_Call) RunAndReturn(run func(context.Context, dto.CreateRequest) (dto.CreateResponse, error)) *MockIService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ReportEvent provides a mock function with given fields: ctx, req
func (_m *MockIService) ReportEvent(ctx context.Context, req dto.ReportEventRequest) (dto.ReportEventResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReportEvent")
	}

	var r0 dto.ReportEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportEventRequest) (dto.ReportEventResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportEventRequest) dto.ReportEventResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.ReportEventResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportEventRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_ReportEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportEvent'
type MockIService_ReportEvent_Call struct {
	*mock.Call
}

// ReportEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.ReportEventRequest
func (_e *MockIService_Expecter) ReportEvent(ctx interface{}, req interface{}) *MockIService_ReportEvent_Call {
	return &MockIService_ReportEvent_Call{Call: _e.mock.On("ReportEvent", ctx, req)}
}

func (_c *MockIService_ReportEvent_Call) Run(run func(ctx context.Context, req dto.ReportEventRequest)) *MockIService_ReportEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ReportEventRequest))
	})
	return _c
}

func (_c *MockIService_ReportEvent_Call) Return(_a0 dto.ReportEventResponse, _a1 error) *MockIService_ReportEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_ReportEvent_Call) RunAndReturn(run func(context.Context, dto.ReportEventRequest) (dto.ReportEventResponse, error)) *MockIService_ReportEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *MockIService) Update(ctx context.Context, req dto.UpdateRequest) (dto.UpdateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.UpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateRequest) (dto.UpdateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateRequest) dto.UpdateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.UpdateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.UpdateRequest
func (_e *MockIService_Expecter) Update(ctx interface{}, req interface{}) *MockIService_Update_Call {
	return &MockIService_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockIService_Update_Call) Run(run func(ctx context.Context, req dto.UpdateRequest)) *MockIService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.UpdateRequest))
	})
	return _c
}

func (_c *MockIService_Update_Call) Return(_a0 dto.UpdateResponse, _a1 error) *MockIService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_Update_Call) RunAndReturn(run func(context.Context, dto.UpdateRequest) (dto.UpdateResponse, error)) *MockIService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
